"""
Django settings for XAAMGA_BACKEND project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hlre6g+_!2nyh*^07&-euy)a861q@#tl0-3=8=to^z9i4i!h5x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     #THIRD PARTY PACKAGES 
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',
    'rest_framework',
    'rest_framework.authtoken',
    "corsheaders",
    "django_countries",
    
    # Local Apps 
    'home',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    # "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'XAAMGA_BACKEND.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'XAAMGA_BACKEND.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configuration de la base de données sur LWS
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'cp2068290p22_xaamga_api_db',
#         'USER': 'cp2068290p22_xaamga_api_user',
#         'PASSWORD': 'Passer@123',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# } 


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'xaamga_api_db',
#         'USER': 'postgres',
#         'PASSWORD': 'passer123',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Authentification par défaut
)

AUTH_USER_MODEL = 'home.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # <-- And here
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.xaamga-ticket.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER ='no-reply@xaamga-ticket.com' 
EMAIL_HOST_PASSWORD = 'BH1.@ky2vQLm'
DEFAULT_FROM_EMAIL = 'no-reply@xaamga-ticket.com'

ALLOWED_HOSTS = ['*', 'localhost', 'localhost:4200', 'https://xaamga-pass.com', 'https://v2.xaamga-ticket.com','https://xaamga-ticket.com','https://www.xaamga-ticket.com']


CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',
    'https://xaamga-pass.com',
    'https://v2.xaamga-ticket.com',
    'http://v2.xaamga-ticket.com',
    'https://xaamga-ticket.com',
    'https://www.xaamga-ticket.com',
    # Add other allowed origins here if needed
]
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:4200',
    'https://xaamga-pass.com',
    'https://v2.xaamga-ticket.com',
    'http://v2.xaamga-ticket.com',
    'https://xaamga-ticket.com',
    'https://www.xaamga-ticket.com',
]


CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

STRIPE_WEBHOOK_SECRET="whsec_CXfv7RfQJgXwk7e5SMKTZWivqiFoWRhu"

ACCOUNT_EMAIL_VERIFICATION = "none"

SOCIAL_SECRET="8494a4c8287596a7a57d2d0ac451bb8f"

BASE_URL="http://localhost:8000"

FRONTEND_URL='https://xaamga-ticket.com'
# FRONTEND_URL="https://v2.xaamga-ticket.com"