# Generated by Django 5.0.6 on 2024-07-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tickettype_order_orderitem_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='mycart',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
