# Generated by Django 5.0.6 on 2024-07-12 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_price_mycart_unit_price_mycart_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('qrcode', models.CharField(max_length=50, null=True)),
                ('pass_type', models.CharField(choices=[('Simple', 'Simple'), ('Gold', 'Gold'), ('Vip', 'Vip'), ('Prestige', 'Prestige')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(null=True)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('control_date', models.DateTimeField(null=True)),
                ('badge_id', models.CharField(max_length=100)),
                ('uid_1', models.CharField(max_length=50, null=True)),
                ('uid_2', models.CharField(max_length=50, null=True)),
                ('badge_type', models.CharField(choices=[('salon', 'Badge salon'), ('event', 'Badget event')], max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderitem')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tickettype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BraceletTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('qrcode', models.CharField(max_length=50, null=True)),
                ('pass_type', models.CharField(choices=[('Simple', 'Simple'), ('Gold', 'Gold'), ('Vip', 'Vip'), ('Prestige', 'Prestige')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(null=True)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('control_date', models.DateTimeField(null=True)),
                ('bracelet_code', models.CharField(max_length=100)),
                ('uid_1', models.CharField(max_length=50, null=True)),
                ('uid_2', models.CharField(max_length=50, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderitem')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tickettype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ETicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('qrcode', models.CharField(max_length=50, null=True)),
                ('pass_type', models.CharField(choices=[('Simple', 'Simple'), ('Gold', 'Gold'), ('Vip', 'Vip'), ('Prestige', 'Prestige')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(null=True)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('control_date', models.DateTimeField(null=True)),
                ('qr_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expiration_date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderitem')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tickettype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('qrcode', models.CharField(max_length=50, null=True)),
                ('pass_type', models.CharField(choices=[('Simple', 'Simple'), ('Gold', 'Gold'), ('Vip', 'Vip'), ('Prestige', 'Prestige')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(null=True)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('control_date', models.DateTimeField(null=True)),
                ('qr_code', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('nfc_tag_1', models.CharField(blank=True, max_length=100, null=True)),
                ('nfc_tag_2', models.CharField(blank=True, max_length=100, null=True)),
                ('is_loaded', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderitem')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tickettype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThermalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('qrcode', models.CharField(max_length=50, null=True)),
                ('pass_type', models.CharField(choices=[('Simple', 'Simple'), ('Gold', 'Gold'), ('Vip', 'Vip'), ('Prestige', 'Prestige')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(null=True)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('control_date', models.DateTimeField(null=True)),
                ('qr_code', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('is_loaded', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderitem')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tickettype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
