# Generated by Django 5.0.6 on 2024-07-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_badgeticket_braceletticket_eticket_physicalticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeticket',
            name='qrcode',
        ),
        migrations.RemoveField(
            model_name='badgeticket',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='braceletticket',
            name='qrcode',
        ),
        migrations.RemoveField(
            model_name='braceletticket',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='eticket',
            name='qrcode',
        ),
        migrations.RemoveField(
            model_name='eticket',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='physicalticket',
            name='qrcode',
        ),
        migrations.RemoveField(
            model_name='physicalticket',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='thermalticket',
            name='qrcode',
        ),
        migrations.RemoveField(
            model_name='thermalticket',
            name='ticket_type',
        ),
    ]
