# Generated by Django 5.0.6 on 2024-07-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_badgeticket_qrcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='badgeticket',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='badgeticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='braceletticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='braceletticket',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='braceletticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eticket',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='eticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='physicalticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='physicalticket',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='physicalticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thermalticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='thermalticket',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='thermalticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
        migrations.DeleteModel(
            name='BadgeTicket',
        ),
        migrations.DeleteModel(
            name='BraceletTicket',
        ),
        migrations.DeleteModel(
            name='ETicket',
        ),
        migrations.DeleteModel(
            name='PhysicalTicket',
        ),
        migrations.DeleteModel(
            name='ThermalTicket',
        ),
    ]
