# Generated by Django 5.0.6 on 2024-07-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_badgeticket_braceletticket_eticket_physicalticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
