# Generated by Django 5.0.6 on 2024-07-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_eticket_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='client_phonenumber',
        ),
        migrations.RemoveField(
            model_name='event',
            name='partner_email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='partner_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='partner_phonenumber',
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.partner'),
        ),
    ]
