# Generated by Django 5.0.6 on 2024-07-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_event_client_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpasscategory',
            old_name='price_with_nfc',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='eventpasscategory',
            name='price_with_qr',
        ),
        migrations.AddField(
            model_name='eventpasscategory',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventpasscategory',
            name='with_nfc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passcategory',
            name='nfc_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='passcategory',
            name='qr_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventpasscategory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ticket_categories', to='home.event'),
        ),
        migrations.AlterField(
            model_name='eventpasscategory',
            name='pass_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ticket_categories', to='home.passcategory'),
        ),
        migrations.AlterField(
            model_name='passcategory',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
