# Generated by Django 5.0.6 on 2024-07-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_price_with_nfc_eventpasscategory_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pass_categories',
        ),
        migrations.AlterUniqueTogether(
            name='eventpasscategory',
            unique_together={('event', 'pass_category')},
        ),
    ]
