# Generated by Django 5.0.6 on 2024-07-15 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_event_pass_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpasscategory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pass_categories', to='home.event'),
        ),
        migrations.AlterField(
            model_name='eventpasscategory',
            name='pass_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pass_categories', to='home.passcategory'),
        ),
    ]
