# Generated by Django 5.0.6 on 2024-07-16 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_eventpasscategory_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeticket',
            name='pass_type',
        ),
        migrations.RemoveField(
            model_name='braceletticket',
            name='pass_type',
        ),
        migrations.RemoveField(
            model_name='eticket',
            name='pass_type',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='pass_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='pass_type',
        ),
        migrations.RemoveField(
            model_name='physicalticket',
            name='pass_type',
        ),
        migrations.RemoveField(
            model_name='thermalticket',
            name='pass_type',
        ),
        migrations.AddField(
            model_name='badgeticket',
            name='pass_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.passcategory'),
        ),
        migrations.AddField(
            model_name='braceletticket',
            name='pass_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.passcategory'),
        ),
        migrations.AddField(
            model_name='eticket',
            name='pass_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.passcategory'),
        ),
        migrations.AddField(
            model_name='mycart',
            name='pass_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_cart', to='home.passcategory'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pass_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='home.passcategory'),
        ),
        migrations.AddField(
            model_name='physicalticket',
            name='pass_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.passcategory'),
        ),
        migrations.AddField(
            model_name='thermalticket',
            name='pass_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.passcategory'),
        ),
        migrations.AlterField(
            model_name='badgeticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.event'),
        ),
        migrations.AlterField(
            model_name='badgeticket',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.orderitem'),
        ),
        migrations.AlterField(
            model_name='badgeticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='braceletticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.event'),
        ),
        migrations.AlterField(
            model_name='braceletticket',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.orderitem'),
        ),
        migrations.AlterField(
            model_name='braceletticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.event'),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.orderitem'),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='physicalticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.event'),
        ),
        migrations.AlterField(
            model_name='physicalticket',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.orderitem'),
        ),
        migrations.AlterField(
            model_name='physicalticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thermalticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.event'),
        ),
        migrations.AlterField(
            model_name='thermalticket',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to='home.orderitem'),
        ),
        migrations.AlterField(
            model_name='thermalticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
