# Generated by Django 5.0.6 on 2024-07-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_badgeticket_pass_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type_of_event',
        ),
    ]
