# Generated by Django 5.0.6 on 2024-07-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_event_type_of_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='braceletprice',
            name='event',
        ),
        migrations.RemoveField(
            model_name='checkinpoint',
            name='event',
        ),
        migrations.RemoveField(
            model_name='drinkspoint',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventbadges',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventbracelet',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventpass',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventteam',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventteam',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exhibitionpoint',
            name='event',
        ),
        migrations.RemoveField(
            model_name='guichetpoint',
            name='event',
        ),
        migrations.RemoveField(
            model_name='passprice',
            name='event',
        ),
        migrations.RemoveField(
            model_name='passpurchase',
            name='event',
        ),
        migrations.RemoveField(
            model_name='passpurchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workshoppoint',
            name='event',
        ),
        migrations.DeleteModel(
            name='ActivityPoint',
        ),
        migrations.DeleteModel(
            name='BraceletPrice',
        ),
        migrations.DeleteModel(
            name='CheckInPoint',
        ),
        migrations.DeleteModel(
            name='DrinksPoint',
        ),
        migrations.DeleteModel(
            name='EventBadges',
        ),
        migrations.DeleteModel(
            name='EventBracelet',
        ),
        migrations.DeleteModel(
            name='EventPass',
        ),
        migrations.DeleteModel(
            name='EventTeam',
        ),
        migrations.DeleteModel(
            name='ExhibitionPoint',
        ),
        migrations.DeleteModel(
            name='GuichetPoint',
        ),
        migrations.DeleteModel(
            name='PassPrice',
        ),
        migrations.DeleteModel(
            name='PassPurchase',
        ),
        migrations.DeleteModel(
            name='WorkshopPoint',
        ),
    ]
