# Generated by Django 5.0.6 on 2024-07-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_customuser_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserdetail',
            name='email_or_phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
