# Generated by Django 5.0.6 on 2024-07-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_enduserdetail_email_or_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserdetail',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
