# Generated by Django 5.0.6 on 2024-08-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_enduserdetail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduserdetail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enduserdetail',
            name='telephone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
