# Generated by Django 5.0.6 on 2024-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpasscategory',
            name='with_nfc',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
