# Generated by Django 5.0.6 on 2024-09-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='enddatetime',
            field=models.DateTimeField(),
        ),
    ]
