# Generated by Django 5.0.6 on 2024-09-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
