# Generated by Django 5.0.6 on 2025-02-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_eventorganizer_eventpartner_eventservice_eventtalent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
