# Generated by Django 5.0.6 on 2025-02-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_otp_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enduserdetail',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
    ]
