# Generated by Django 5.1.6 on 2025-02-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_customuser_is_google_enduserdetail_is_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_stripe_token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
