# Generated by Django 5.1.6 on 2025-02-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_order_order_id_order_payment_stripe_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='XM-0000', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
