# Generated by Django 5.0.6 on 2025-02-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeticket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='badgeticket',
            name='due_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='badgeticket',
            name='quantity',
            field=models.CharField(default=1, max_length=12),
        ),
        migrations.AddField(
            model_name='braceletticket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='braceletticket',
            name='due_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='braceletticket',
            name='quantity',
            field=models.CharField(default=1, max_length=12),
        ),
        migrations.AddField(
            model_name='eticket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eticket',
            name='due_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='eticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etickets', to='home.order'),
        ),
        migrations.AddField(
            model_name='eticket',
            name='quantity',
            field=models.CharField(default=1, max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalticket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalticket',
            name='due_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalticket',
            name='quantity',
            field=models.CharField(default=1, max_length=12),
        ),
        migrations.AddField(
            model_name='thermalticket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='thermalticket',
            name='due_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='thermalticket',
            name='quantity',
            field=models.CharField(default=1, max_length=12),
        ),
    ]
