# Generated by Django 5.0.6 on 2025-03-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_badgeticket_created_date_badgeticket_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handles_partner_events', to='home.partner'),
        ),
    ]
