# Generated by Django 5.0.6 on 2025-03-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_event_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('partner_1', 'Partner 1'), ('partner_2', 'Partner 2'), ('partner_3', 'Partner 3')], max_length=255),
        ),
    ]
