# Generated by Django 5.0.6 on 2025-03-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_partner_partner_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
