# Generated by Django 5.0.6 on 2025-03-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_rename_second_name_admin_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='enduserdetail',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
